Integrate NCES in ontolearn-web service and fix dllearner binding script in examples
dice-group/Ontolearn pull request #450
Opened 2024-10-15 14:24 UTC by Jean-KOUAGOU

This pull request addresses the issue#408: https://github.com/dice-group/Ontolearn/issues/408, and updates the dllearner binder script such that positive and negative examples initially given here: https://github.com/dice-group/Ontolearn/blob/develop/examples/dl_learner.py#L39 are first sent to the PosNegLPStandard class as required by the binder and most class expression learners, inc. Drill, EvoLearner, CELOE, CLIP, etc

Please review and merge

2024-10-16 09:16 UTC, Demirrr requested changes

2024-10-16 09:16 UTC, Demirrr commented on ontolearn/concept_learner.py
> +            return [best.concept for best in self.best_predictions[:n]]
Why do we need this converation ?

2024-10-16 09:16 UTC, Demirrr commented on ontolearn/scripts/run.py
We need to be able to train NCES from scratch or upload a pretrained model. With your changes, we cannot train NCES from scratch. Please follow the Drill integration

2024-10-16 09:16 UTC, Demirrr commented on examples/dl_learner.py
Thank you this would work

2024-10-16 09:31 UTC, Jean-KOUAGOU commented on ontolearn/concept_learner.py
> +            return [best.concept for best in self.best_predictions[:n]]
By default, other concept learners, including Drill output a list of concepts, not nodes. This is why I am converting. Moreover, NCES uses its own node class for the moment. In the future, if necessary, we might investigate the use of OENode which is currently tailored towards search-based approaches.

2024-10-16 09:37 UTC, Demirrr commented on ontolearn/scripts/run.py
Yes please!

2024-10-16 09:40 UTC, Demirrr commented on ontolearn/concept_learner.py
> +            return [best.concept for best in self.best_predictions[:n]]
We cannot return OENode. Since we learn OWL Class expressions, return results must fulfill `Union[OWLClassExpression, Iterable[OWLClassExpression]]`.

2024-10-17 08:04 UTC, Demirrr commented
Could you please ensure that no fixed paths are being used?
The following lines must not contain only fixed paths

1. https://github.com/dice-group/Ontolearn/blob/49427edac0585d29e426e6ee1d40317f94e589bf/ontolearn/scripts/run.py#L59
2. https://github.com/dice-group/Ontolearn/blob/49427edac0585d29e426e6ee1d40317f94e589bf/ontolearn/scripts/run.py#L92
3. https://github.com/dice-group/Ontolearn/blob/49427edac0585d29e426e6ee1d40317f94e589bf/ontolearn/scripts/run.py#L106 There is no reason to force a user to use conex embeddings

4. https://github.com/dice-group/Ontolearn/blob/49427edac0585d29e426e6ee1d40317f94e589bf/ontolearn/scripts/run.py#L149

`owl_learner` must follow the same interface.
https://github.com/dice-group/Ontolearn/blob/49427edac0585d29e426e6ee1d40317f94e589bf/ontolearn/scripts/run.py#L195

2024-10-17 10:51 UTC, Jean-KOUAGOU commented
1. , 2., 3., 4.

`parser.add_argument("--path_of_nces_embeddings", type=str, default="./NCESData/")` was removed. It now takes input from the user (same as Drill data["path_embeddings"])

`if not os.path.exists(f"./NCESData/{kb_name}/embeddings/ConEx_entity_embeddings.csv")`. Same as above. The function has been modified, and takes input from the user. It is only when the path provided by the user does not exist that it looks from embeddings online. This is because NCES needs embeddings to run, not like Drill which can run without embeddings.

`owl_learner` must follow the same interface. This has been fixed. No check whether it is an NCES instance. NCES takes PosNegLPStandard as the other learners now.

## Note: 
If I completely remove the possibility to download embeddings for NCES, the user will have to go download them manually if he still needs to test NCES. As it currently is, the user can provide any embeddings, and they will be used.

2024-10-17 10:56 UTC, Jean-KOUAGOU commented
## Another Note

NCES is trained from scratch if the provided path for pretained models does not contain any files

2024-10-17 12:55 UTC, Demirrr commented
Can you please follow the enumeration ? and fix the each point individually.

> 1. , 2., 3., 4.

What does this enumeration mean ? Can you please nextime explicitly state whether the required is done or not?

This function is still in the script. This needs to be removed.
```
def get_embedding_path(ftp_link: str, kb_path_arg: str)->str:
        return f"./NCESData/{kb_name}/embeddings/ConEx_entity_embeddings.csv"

```


**Please** follow the same structure of preparting an owl reasoner as we have done for DRILL and TDL

2024-10-17 12:56 UTC, Demirrr commented
1. Is still not being fixed https://github.com/dice-group/Ontolearn/blob/49427edac0585d29e426e6ee1d40317f94e589bf/ontolearn/scripts/run.py#L59

2024-10-17 13:27 UTC, Jean-KOUAGOU commented
> 1. Is still not being fixed https://github.com/dice-group/Ontolearn/blob/49427edac0585d29e426e6ee1d40317f94e589bf/ontolearn/scripts/run.py#L59

You are probably looking at an old commit. New link here: https://github.com/dice-group/Ontolearn/blob/nces_web_and_fix_dllearner_binder/ontolearn/scripts/run.py#L55

2024-10-17 13:29 UTC, Jean-KOUAGOU commented
I replied for 1., 2., 3., 4.

They have been resolved but with notes awaiting for your confirmation. I will write notes down here again.

parser.add_argument("--path_of_nces_embeddings", type=str, default="./NCESData/") was removed. It now takes input from the user (same as Drill data["path_embeddings"])

if not os.path.exists(f"./NCESData/{kb_name}/embeddings/ConEx_entity_embeddings.csv"). Same as above. The function has been modified, and takes input from the user. It is only when the path provided by the user does not exist that it looks for embeddings online. This is because NCES needs embeddings to run, not like Drill which can run without embeddings.

owl_learner must follow the same interface. This has been fixed. No check whether it is an NCES instance. NCES takes PosNegLPStandard as the other learners now.

### Note 1:
If I completely remove the possibility to download embeddings for NCES, the user will have to download them manually in case he does not have any emeddings and still needs to test NCES. As it currently is, the user can provide any embeddings and they will be used. But feel free to request that I remove any possibility to download data.

### Note2:
NCES is trained from scratch if the provided path for pretained models does not contain any files

2024-10-17 13:59 UTC, Demirrr commented
> They have been resolved but with notes awaiting for your confirmation

If they have been resolved, please push them.

2024-10-17 14:03 UTC, Demirrr requested changes

2024-10-17 14:03 UTC, Demirrr commented on examples/train_nces.py
>      path_of_embeddings = f"./NCESData/{kb}/embeddings/ConEx_entity_embeddings.csv"
We cannot use a fixed path!

2024-10-17 14:03 UTC, Demirrr commented on ontolearn/scripts/run.py
> +def get_embedding_path(ftp_link: str, path_embeddings: str, kb_path_arg: str)->str:
Please do not use fixed names. Aynthing related to the preperation of NCES must be in get_nces()

2024-10-17 14:03 UTC, Demirrr commented on ontolearn/scripts/run.py
> +                    path_of_embeddings=get_embedding_path("https://files.dice-research.org/projects/NCES/NCES_Ontolearn_Data/NCESData.zip", data.get("path_embeddings", None), args.path_knowledge_base
**Please DO NOT use a fixed embedding path**

2024-10-17 14:03 UTC, Demirrr commented on ontolearn/scripts/run.py
> +    if data.get("path_to_pretrained_nces", None) and os.path.isdir(data["path_to_pretrained_nces"]) and glob.glob("*.pt"):
Please do not use glob.plot with ** * **. Input items must be fixed

2024-10-23 04:48 UTC, LckyLke commented on examples/concept_learning_cv_evaluation.py
> +                pretrained_model_name=["LSTM", "GRU", "SetTransformer"]
```suggestion
                learner_names=["LSTM", "GRU", "SetTransformer"],
```
-> this should be learner names? Also why was the comma removed?

2024-10-23 04:50 UTC, LckyLke commented on examples/concept_learning_cv_evaluation.py
> +                pretrained_model_name=["LSTM", "GRU", "SetTransformer"]
after these changes this script runs, but still throws the following error:
`AttributeError: 'NoneType' object has no attribute 'shape'`

for line 63 in class BaseNCES:
`self.input_size = self.instance_embeddings.shape[1]`

2024-10-23 05:12 UTC, LckyLke commented on examples/dl_learner.py
> +    lp = PosNegLPStandard(pos=positives, neg=positives)
Import for this is missing

2024-10-23 07:31 UTC, Jean-KOUAGOU commented
Hi. If a comma or import is missing, it must have been a typo. Please feel
free to add them.

On Wed, Oct 23, 2024, 07:13 Luke Friedrichs ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In examples/dl_learner.py
> <https://github.com/dice-group/Ontolearn/pull/450#discussion_r1811865794>:
>
> > @@ -36,9 +38,14 @@
>      p = examples['positive_examples']
>      n = examples['negative_examples']
>
> -    best_pred_celoe = celoe.fit(pos=p, neg=n, max_runtime=1).best_hypothesis()
> +    positives = {OWLNamedIndividual(IRI.create(i)) for i in p}
> +    negatives = {OWLNamedIndividual(IRI.create(i)) for i in n}
> +
> +    lp = PosNegLPStandard(pos=positives, neg=positives)
>
> Import for this is missing
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dice-group/Ontolearn/pull/450#pullrequestreview-2387165179>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK4X4ETCP32LHK4MAXPQ3YTZ44V67AVCNFSM6AAAAABP7JIJI2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOBXGE3DKMJXHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-24 12:31 UTC, alkidbaci commented on examples/concept_learning_cv_evaluation.py
> +                pretrained_model_name=["LSTM", "GRU", "SetTransformer"]
@LckyLke that happens because you need to pass the path of embeddings. 
There are a few other errors with this script which are not related with this PR. 
Ill open an issue for that.

2024-10-24 13:21 UTC, alkidbaci commented on ontolearn/concept_learner.py
> +            storage_path = f'NCES-Experiment-{currentDateAndTime.strftime("%H:%M:%S")}'
The colon character `:` is not allowed in Windows filenames and therefore an error will occur in this systems.
I'll change this to the following:
```suggestion
            storage_path = f'NCES-Experiment-{currentDateAndTime.strftime("%H-%M-%S")}'
```

2024-10-25 08:57 UTC, merged