Fix for issue #467 and prediction caching lru
dice-group/Ontolearn pull request #469
Opened 2024-11-04 06:17 UTC by LckyLke

fix for issue #467

2024-11-04 13:13 UTC, Demirrr requested changes
get_predictions function seems to be overcomplicated. 
Please simplify these lines. If an entity or a relation is not found, then we should throw an KeyError exception
 ```
       if h is not None:
            if (self.model.entity_to_idx.get(h, None)) is None:
                return
            h = [h]
        if r is not None:
            if (self.model.relation_to_idx.get(r, None)) is None:
                return
            r = [r]
        if t is not None:
            if (self.model.entity_to_idx.get(t, None)) is None:
                return
            t = [t]
``` 
Caching the results can be moved to outside of this function
Do you think that we should simply it?

2024-11-04 13:13 UTC, Demirrr commented on ontolearn/owl_neural_reasoner.py
> +
Could you please ensure that there is no unnecessary space between lines?

2024-11-04 13:13 UTC, Demirrr commented on ontolearn/owl_neural_reasoner.py
> +
Could you please ensure that there is no unnecessary space between lines?

2024-11-04 13:13 UTC, Demirrr commented on ontolearn/owl_neural_reasoner.py
> +            return
What is the purpose of returning None ?

2024-11-04 13:13 UTC, Demirrr commented on ontolearn/owl_neural_reasoner.py
> +            return
You may want to do the following. 

`if cache_key in self._prediction_cache` is True, then return the result of a function A, otherwise return the result of a function B.

2024-11-05 08:38 UTC, Demirrr approved these changes

2024-11-05 08:58 UTC, merged

2024-11-05 09:00 UTC, Demirrr commented
Did you fix the pytest error?

2024-11-05 09:02 UTC, LckyLke commented
> Did you fix the pytest error?

oh i think i missed that - should i revert?

2024-11-05 09:16 UTC, LckyLke commented
```py
    def abox(self, str_iri: str) -> Generator[
        Tuple[
            Tuple[OWLNamedIndividual, OWLProperty, OWLClass],
            Tuple[OWLObjectProperty, OWLObjectProperty, OWLNamedIndividual],
            Tuple[OWLObjectProperty, OWLDataProperty, OWLLiteral]], None,None ]:
        # Initialize an owl named individual object.
        subject_ = OWLNamedIndividual(str_iri)
        # Return a triple indicating the type.
        for cl in self.get_type_individuals(str_iri):
            yield subject_,OWLProperty("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"), cl

        # Return a triple based on an object property.
        for op in self.object_properties_in_signature():
            for o in self.get_object_property_values(str_iri, op):
                yield subject_, op, o

        # Return a triple based on a data property.
        for dp in self.data_properties_in_signature():  # pragma: no cover
            print("these data properties are in the signature: ", dp.str)
            for l in self.get_data_property_values(str_iri, dp):
                yield subject_, dp, l
```
It is caused by the abox function trying to get the data properties - which itself is not supported yet - but if the kg does not contain any, this will cause the key error ig.  So should we remove this part for now? Or is raising an error not a good idea - because how should we handle the situation if we want to support data properties?

2024-11-05 10:23 UTC, Demirrr commented
> > Did you fix the pytest error?
> 
> oh i think i missed that - should i revert?

Yes please!

2024-11-05 10:23 UTC, Demirrr commented
> ```python
>     def abox(self, str_iri: str) -> Generator[
>         Tuple[
>             Tuple[OWLNamedIndividual, OWLProperty, OWLClass],
>             Tuple[OWLObjectProperty, OWLObjectProperty, OWLNamedIndividual],
>             Tuple[OWLObjectProperty, OWLDataProperty, OWLLiteral]], None,None ]:
>         # Initialize an owl named individual object.
>         subject_ = OWLNamedIndividual(str_iri)
>         # Return a triple indicating the type.
>         for cl in self.get_type_individuals(str_iri):
>             yield subject_,OWLProperty("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"), cl
> 
>         # Return a triple based on an object property.
>         for op in self.object_properties_in_signature():
>             for o in self.get_object_property_values(str_iri, op):
>                 yield subject_, op, o
> 
>         # Return a triple based on a data property.
>         for dp in self.data_properties_in_signature():  # pragma: no cover
>             print("these data properties are in the signature: ", dp.str)
>             for l in self.get_data_property_values(str_iri, dp):
>                 yield subject_, dp, l
> ```
> 
> It is caused by the abox function trying to get the data properties - which itself is not supported yet - but if the kg does not contain any, this will cause the key error ig. So should we remove this part for now? Or is raising an error is not a good idea - because how should we handle the situation if we want to support data properties?

I see. Let's discuss it internally.