Merge TripleStoreKnowledgeBase and TripleStore
dice-group/Ontolearn pull request #497
Opened 2024-11-25 15:28 UTC by Jean-KOUAGOU

I have implemented a simple merge of TripleStore and TripleStoreKnowledgeBase. Tests work locally. Please review and merge

2024-11-29 10:22 UTC, Demirrr requested changes
You didn't really merge TripleStoreKnowledgeBase and TripleStore but rather put already defined class of TripleStoreKnowledgeBase into TripleStore. What is the benefits of this ?

2024-11-29 10:22 UTC, Demirrr commented on tests/test_triplestore.py
> +
Remove
if __name__ == "__main__":
    test_triplestore = TestTriplestore()
    test_triplestore.test_remote_triplestore_dbpedia_tdl()
    
 No need these three lines.

2024-11-29 10:22 UTC, Demirrr commented on tests/test_triplestore.py
> +            print(h)
No need to print

2024-11-29 10:22 UTC, Demirrr commented on tests/test_triplestore.py
>              pass
pass is problematic. This is not a really test

2024-11-29 10:22 UTC, Demirrr commented on ontolearn/triple_store.py
> +        self.g = TripleStoreReasonerOntology(url=url)
This is incorrect. We cannot have TripleStoreOntology, TripleStoreReasoner, and TripleStoreReasonerOntology, can we ?

2024-12-02 13:43 UTC, alkidbaci commented
I noticed that `TripleStore` class is now inheriting from `KnowledgeBase` which is against the main reason we have `TripleStore` class in the first place. Becase of that we have to set the reasoner and the ontology of that class, and thats why we have `TripleStoreOntology`, `TripleStoreReasoner` and `TripleStoreReasonerOntology` at the same class.
It's kind of the right direction but not quite the right way. 

TDL and Drill works. Drill tried only on family dataset.

These changes can be considered temporary but I suggest we have a more long lasting solution for this problem.

2024-12-09 14:57 UTC, closed without merging