Class expression learning on DBpedia
dice-group/Ontolearn pull request #506
Opened 2024-12-10 15:00 UTC by Jean-KOUAGOU

- I have added a script in examples to benchmark Drill and TDL on DBpedia

- I have also slightly modified the query_results function in TripleStore so multiple attempts are made in case the endpoint does not respond. This has proven useful during benchmarking

2024-12-10 15:07 UTC, Demirrr commented
Thank you all looks good! 

Could you please report the average runtimes and f1 scores in https://github.com/dice-group/Ontolearn?tab=readme-ov-file#benchmark-results?
Please also indicate that these results are related to the training performance, not generalization

2024-12-10 15:45 UTC, Jean-KOUAGOU commented
Sure I will report results

On Tue, Dec 10, 2024, 16:07 Caglar Demir ***@***.***> wrote:

> Thank you all looks good!
>
> Could you please report the average runtimes and f1 scores in
> https://github.com/dice-group/Ontolearn?tab=readme-ov-file#benchmark-results
> ?
> Please also indicate that these results are related to the training
> performance, not generalization
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dice-group/Ontolearn/pull/506#issuecomment-2531947656>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK4X4EXQTCESZEN5WZMTVVT2E37THAVCNFSM6AAAAABTLLVYCGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZRHE2DONRVGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-11 08:42 UTC, Demirrr requested changes
1. DBpedia example script does not contain any explanation. We should give an effort to explain the examples for the users [see this example](https://github.com/dice-group/Ontolearn/blob/79c58e8c5fd58793f16079d4bfb03d578bc14d19/examples/retrieval_eval.py#L1)
2. query_results only sends the sparql query to triple store and return it back. No need additional functionalities, e.g. sending sparql multiple times or returning potentially None.
3. The result of dbpedia script should be reported in the README benchmark results section

2024-12-11 08:42 UTC, Demirrr commented on examples/owl_class_expresion_learning_dbpedia.py
> +"""$ python examples/retrieval_eval.py --path_kg "https://dbpedia.data.dice-research.org/sparql"
Could you please explain the script ?

2024-12-11 08:42 UTC, Demirrr commented on ontolearn/triple_store.py
> +        while True:
There is no need this while loop. If the connection is not in place or timeout is not specified for the request, then we should throw error instead of returning None. Therefore, please remove your changes.

2024-12-11 09:05 UTC, Jean-KOUAGOU commented
Sure, I will fix requested changes

On Wed, Dec 11, 2024, 09:43 Caglar Demir ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
>    1. DBpedia example script does not contain any explanation. We should
>    give an effort to explain the examples for the users see this example
>    <https://github.com/dice-group/Ontolearn/blob/79c58e8c5fd58793f16079d4bfb03d578bc14d19/examples/retrieval_eval.py#L1>
>    2. query_results only sends the sparql query to triple store and
>    return it back. No need additional functionalities, e.g. sending sparql
>    multiple times or returning potentially None.
>    3. The result of dbpedia script should be reported in the README
>    benchmark results section
>
> ------------------------------
>
> In examples/owl_class_expresion_learning_dbpedia.py
> <https://github.com/dice-group/Ontolearn/pull/506#discussion_r1879615348>:
>
> > @@ -0,0 +1,149 @@
> +"""$ python examples/retrieval_eval.py --path_kg "https://dbpedia.data.dice-research.org/sparql"
>
> Could you please explain the script ?
> ------------------------------
>
> In ontolearn/triple_store.py
> <https://github.com/dice-group/Ontolearn/pull/506#discussion_r1879619333>:
>
> > @@ -1195,4 +1195,16 @@ def query(self, sparql: str):
>          yield from self.g.query(sparql_query=sparql)
>
>      def query_results(self, sparql: str):
> -        return self.g.query(sparql_query=sparql)
> +        trials = 0
> +        response = None
> +        while True:
>
> There is no need this while loop. If the connection is not in place or
> timeout is not specified for the request, then we should throw error
> instead of returning None. Therefore, please remove your changes.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dice-group/Ontolearn/pull/506#pullrequestreview-2494778291>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK4X4EQWGJ6R6A65FIVRUPT2E73KDAVCNFSM6AAAAABTLLVYCGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJUG43TQMRZGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-11 14:01 UTC, Demirrr requested changes
As previously stated, please add your results in 
**benchmark-results** section
not under **Learning OWL Class Expressions over DBpedia**
https://github.com/dice-group/Ontolearn/tree/cel_on_dbpedia?tab=readme-ov-file#benchmark-results

2024-12-13 08:07 UTC, Demirrr approved these changes
Thank you for the PR!

2024-12-13 08:07 UTC, merged